name: Protect Directory

on:
  pull_request:

jobs:
  protect-directory:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set directory path
      run: echo "RESTRICTED_PATH=restricted/touch-me-not" >> $GITHUB_ENV

    - name: Check for changes in restricted directory
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^${{ env.RESTRICTED_PATH }}"
        if [ $? -eq 0 ]; then
          echo "Error: Changes in restricted-directory are not allowed."
          exit 1
        fi
