name: Protect Directory

on:
  push:
    paths:
      - 'restricted/touch-me-not'  # Trigger on any file changes
  pull_request:
    paths:
      - 'restricted/touch-me-not'  # Trigger on any pull request

jobs:
  protect-directory:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check for changes in restricted directory
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^restricted-directory/'; then
          echo "Error: Changes in restricted-directory are not allowed."
          exit 1
        fi
